application: personalwebsite-1153
version: 1
runtime: python
api_version: 1

default_expiration: "0d 1m"

handlers:
- url: /images/(.*\.(gif|png|jpg|ico))
  static_files: images/\1
  upload: (.*\.(gif|png|jpg|ico))
  expiration: "0d 10m"

- url: /(.*\.(pdf|js|css))
  static_files: \1
  upload: (.*\.(pdf|js|css))
  expiration: "0d 5m"

- url: /robots.txt
  static_files: robots.txt
  upload: robots.txt

- url: .*
  script: main.py
