application: personalwebsite-1153
version: 1
runtime: python
api_version: 1

default_expiration: "4d 5h"

handlers:
- url: /(.*\.(pdf|gif|png|jpg|ico|js|css))
  static_files: \1
  upload: (.*\.(pdf|gif|png|jpg|ico|js|css))
  expiration: "4d 5h"

- url: /robots.txt
  static_files: robots.txt
  upload: robots.txt

- url: .*
  script: main.py
